name = "hex-primality-mathlib"
defaultTargets = ["HexPrimalityMathlib"]

leanOptions = [
  { name = "doc.verso", value = true },
  { name = "doc.verso.suggestions", value = false },
]

[[require]]
name = "HexPrimality"
git = "https://github.com/leanprover/hex-primality.git"
rev = "d5b5d9eb91e39ad187b011e280da6bf80b6fe5b6"

[[require]]
name = "mathlib"
git = "https://github.com/leanprover-community/mathlib4.git"
rev = "v4.34.0-rc2"

[[lean_lib]]
name = "HexPrimalityMathlib"
